version: '2'
services:
  db:
    image: linguofeng/rpi-postgres
    ports:
      - "5432:5432"

  redis:  
    image: hypriot/rpi-redis

  rabbitmq:
    image: wsrak/rpi-rabbitmq:v3.5.7
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    depends_on:
      - db
    command: bash -c "sleep 5;python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
    ports:
      - "8000:8000"
    links:
      - db
      - worker

  worker:  
    build: .
    environment:
      - C_FORCE_ROOT=true
      - DATABASE_HOST=postgresql
      - BROKER_URL=amqp://guest:guest@rabbitmq//
    command: bash -c "while ! nc -z rabbitmq 5672; do sleep 1; done ; celery -A lamps worker -E -l info --concurrency=2"
    volumes:
      - .:/code
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
    links:
      - db:db
      - rabbitmq
      - redis
